# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nlm.proto',
  package='nlm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tnlm.proto\x12\x03nlm\"7\n\tGraphNode\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05props\x18\x03 \x01(\t\"h\n\rGraphRelation\x12\x1d\n\x05start\x18\x01 \x01(\x0b\x32\x0e.nlm.GraphNode\x12\x1b\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x0e.nlm.GraphNode\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\r\n\x05props\x18\x04 \x01(\t\"T\n\x0bGraphOutput\x12\x1c\n\x02gn\x18\x01 \x01(\x0b\x32\x0e.nlm.GraphNodeH\x00\x12 \n\x02gr\x18\x02 \x01(\x0b\x32\x12.nlm.GraphRelationH\x00\x42\x05\n\x03gop\"\'\n\x06\x45ntity\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"G\n\x08NLMInput\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\x12\x1d\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x0b.nlm.Entity\"\x19\n\tRawString\x12\x0c\n\x04text\x18\x01 \x01(\t2\xd2\x01\n\x03NLM\x12/\n\tStrRecall\x12\x0e.nlm.RawString\x1a\x10.nlm.GraphOutput\"\x00\x12.\n\tNLURecall\x12\r.nlm.NLMInput\x1a\x10.nlm.GraphOutput\"\x00\x12.\n\nNodeRecall\x12\x0e.nlm.GraphNode\x1a\x0e.nlm.GraphNode\"\x00\x12:\n\x0eRelationRecall\x12\x12.nlm.GraphRelation\x1a\x12.nlm.GraphRelation\"\x00\x62\x06proto3')
)




_GRAPHNODE = _descriptor.Descriptor(
  name='GraphNode',
  full_name='nlm.GraphNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='nlm.GraphNode.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='nlm.GraphNode.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props', full_name='nlm.GraphNode.props', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=73,
)


_GRAPHRELATION = _descriptor.Descriptor(
  name='GraphRelation',
  full_name='nlm.GraphRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='nlm.GraphRelation.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='nlm.GraphRelation.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='nlm.GraphRelation.kind', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props', full_name='nlm.GraphRelation.props', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=179,
)


_GRAPHOUTPUT = _descriptor.Descriptor(
  name='GraphOutput',
  full_name='nlm.GraphOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gn', full_name='nlm.GraphOutput.gn', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gr', full_name='nlm.GraphOutput.gr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='gop', full_name='nlm.GraphOutput.gop',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=181,
  serialized_end=265,
)


_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='nlm.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='nlm.Entity.entity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='nlm.Entity.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=306,
)


_NLMINPUT = _descriptor.Descriptor(
  name='NLMInput',
  full_name='nlm.NLMInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nlm.NLMInput.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intent', full_name='nlm.NLMInput.intent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entities', full_name='nlm.NLMInput.entities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=379,
)


_RAWSTRING = _descriptor.Descriptor(
  name='RawString',
  full_name='nlm.RawString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nlm.RawString.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=406,
)

_GRAPHRELATION.fields_by_name['start'].message_type = _GRAPHNODE
_GRAPHRELATION.fields_by_name['end'].message_type = _GRAPHNODE
_GRAPHOUTPUT.fields_by_name['gn'].message_type = _GRAPHNODE
_GRAPHOUTPUT.fields_by_name['gr'].message_type = _GRAPHRELATION
_GRAPHOUTPUT.oneofs_by_name['gop'].fields.append(
  _GRAPHOUTPUT.fields_by_name['gn'])
_GRAPHOUTPUT.fields_by_name['gn'].containing_oneof = _GRAPHOUTPUT.oneofs_by_name['gop']
_GRAPHOUTPUT.oneofs_by_name['gop'].fields.append(
  _GRAPHOUTPUT.fields_by_name['gr'])
_GRAPHOUTPUT.fields_by_name['gr'].containing_oneof = _GRAPHOUTPUT.oneofs_by_name['gop']
_NLMINPUT.fields_by_name['entities'].message_type = _ENTITY
DESCRIPTOR.message_types_by_name['GraphNode'] = _GRAPHNODE
DESCRIPTOR.message_types_by_name['GraphRelation'] = _GRAPHRELATION
DESCRIPTOR.message_types_by_name['GraphOutput'] = _GRAPHOUTPUT
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['NLMInput'] = _NLMINPUT
DESCRIPTOR.message_types_by_name['RawString'] = _RAWSTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphNode = _reflection.GeneratedProtocolMessageType('GraphNode', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHNODE,
  '__module__' : 'nlm_pb2'
  # @@protoc_insertion_point(class_scope:nlm.GraphNode)
  })
_sym_db.RegisterMessage(GraphNode)

GraphRelation = _reflection.GeneratedProtocolMessageType('GraphRelation', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHRELATION,
  '__module__' : 'nlm_pb2'
  # @@protoc_insertion_point(class_scope:nlm.GraphRelation)
  })
_sym_db.RegisterMessage(GraphRelation)

GraphOutput = _reflection.GeneratedProtocolMessageType('GraphOutput', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHOUTPUT,
  '__module__' : 'nlm_pb2'
  # @@protoc_insertion_point(class_scope:nlm.GraphOutput)
  })
_sym_db.RegisterMessage(GraphOutput)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'nlm_pb2'
  # @@protoc_insertion_point(class_scope:nlm.Entity)
  })
_sym_db.RegisterMessage(Entity)

NLMInput = _reflection.GeneratedProtocolMessageType('NLMInput', (_message.Message,), {
  'DESCRIPTOR' : _NLMINPUT,
  '__module__' : 'nlm_pb2'
  # @@protoc_insertion_point(class_scope:nlm.NLMInput)
  })
_sym_db.RegisterMessage(NLMInput)

RawString = _reflection.GeneratedProtocolMessageType('RawString', (_message.Message,), {
  'DESCRIPTOR' : _RAWSTRING,
  '__module__' : 'nlm_pb2'
  # @@protoc_insertion_point(class_scope:nlm.RawString)
  })
_sym_db.RegisterMessage(RawString)



_NLM = _descriptor.ServiceDescriptor(
  name='NLM',
  full_name='nlm.NLM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=409,
  serialized_end=619,
  methods=[
  _descriptor.MethodDescriptor(
    name='StrRecall',
    full_name='nlm.NLM.StrRecall',
    index=0,
    containing_service=None,
    input_type=_RAWSTRING,
    output_type=_GRAPHOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NLURecall',
    full_name='nlm.NLM.NLURecall',
    index=1,
    containing_service=None,
    input_type=_NLMINPUT,
    output_type=_GRAPHOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NodeRecall',
    full_name='nlm.NLM.NodeRecall',
    index=2,
    containing_service=None,
    input_type=_GRAPHNODE,
    output_type=_GRAPHNODE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RelationRecall',
    full_name='nlm.NLM.RelationRecall',
    index=3,
    containing_service=None,
    input_type=_GRAPHRELATION,
    output_type=_GRAPHRELATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NLM)

DESCRIPTOR.services_by_name['NLM'] = _NLM

# @@protoc_insertion_point(module_scope)
